#!/usr/bin/perl

# fájlokban keres mintát és kiírja az első találat helyét
# bgrep 'B\x65\131' valami masik
# bgrep -x 65f8 *
#  -b: a blokkok számát írja ki (512 bájtos)

if ( $ARGV[0] eq '-x' ) {
	shift;
	( $REGEX = $ARGV[0] ) =~ s/(..)/\\x$1/g;
	shift;
} elsif ( $ARGV[0] eq '-b' ) {
	$BLOCK = true;
	shift;
	$REGEX = $ARGV[0];
	shift;
} else {
	$REGEX = $ARGV[0];
	shift;
}

$rs=$/; undef $/;
foreach $i (@ARGV) {

	open(F,"< $i") or die "Nincs ilyen file: $i\n";
	$F = <F>;
	close(F);
	pos($F)=0;
	if ($F =~ /^(.*)$REGEX/sg) {
		$POS = length($1);
		if ($BLOCK) {
			print ($POS/512); print "\n";
		} else {
			printf "%-15s: ", $i;
			print join(" ", map { sprintf "%02X", $_ } unpack("C*",pack("L",$POS)));
			print " (".$POS.")\n";
		}
	}

}
$/=$rs;
