#!/bin/bash

# a Taninform e-naplóból kapott "Évvégi eredmények" xls végéhez
# oda van csapva egy HTML dokumentum - azt szedi le.

set -e

# a tmp könyvtárba tesszük a backup fájlokat
[ ! -d tmp ] && mkdir tmp

for f in $*; do
	n=$( ./bgrep -b '\r<!DOCTYPE' $f )
	[ -z "$n" ] && continue
	cp $f tmp
	dd if=tmp/$f of=$f bs=512 count=$n
	dd if=tmp/$f of=${f%.xls}.html bs=512 skip=$n
done

